Imports System.Text
Imports System.Drawing

''' <summary>
''' Generates FreeBASIC + Window9 source code from a W9FormDesign model.
''' Produces clean, well-structured .bas files following the patterns from
''' Ronen's chatbot templates (enum IDs, proportional resize, event loop).
''' </summary>
Public Module W9CodeGenerator

    ''' <summary>Generate complete FreeBASIC source from a form design.</summary>
    Public Function GenerateCode(design As W9FormDesign) As String
        Dim sb As New StringBuilder()

        ' File header
        EmitHeader(sb, design)
        sb.AppendLine()

        ' Include
        EmitIncludes(sb)
        sb.AppendLine()

        ' Base dimensions for scaling
        If design.ProportionalResize Then
            EmitScalingConstants(sb, design)
            sb.AppendLine()
        End If

        ' Linux compatibility defines
        EmitLinuxCompat(sb)
        sb.AppendLine()

        ' Gadget ID enum
        EmitGadgetEnum(sb, design)
        sb.AppendLine()

        ' Menu ID enum (if menus exist)
        If design.MenuItems.Count > 0 Then
            EmitMenuEnum(sb, design)
            sb.AppendLine()
        End If

        ' Shortcut ID enum (if keyboard shortcuts)
        If design.HasKeyboardShortcut Then
            EmitShortcutEnum(sb, design)
            sb.AppendLine()
        End If

        ' Shared variables
        EmitSharedVars(sb, design)
        sb.AppendLine()

        ' Event handler stubs for buttons
        EmitEventHandlerStubs(sb, design)
        sb.AppendLine()

        ' Resize handler
        If design.ProportionalResize AndAlso design.HandleResize Then
            EmitResizeHandler(sb, design)
            sb.AppendLine()
        End If

        ' Main section
        EmitMainSection(sb, design)
        sb.AppendLine()

        ' Event loop
        EmitEventLoop(sb, design)
        sb.AppendLine()

        ' Helper reference (commented out API reference)
        EmitHelperReference(sb, design)

        Return sb.ToString()
    End Function

    ' =========================================================================
    ' Section emitters
    ' =========================================================================

    Private Sub EmitHeader(sb As StringBuilder, design As W9FormDesign)
        sb.AppendLine("' ============================================================================")
        sb.AppendLine("' " & design.FormTitle & " - FreeBASIC + Window9")
        sb.AppendLine("' ============================================================================")
        sb.AppendLine("' Generated by FBEditor v5.0.0 Visual Form Designer")
        sb.AppendLine("' Date: " & DateTime.Now.ToString("yyyy-MM-dd HH:mm"))
        sb.AppendLine("' ============================================================================")
        sb.AppendLine("' Compile: fbc -s gui " & SanitizeFilename(design.FormTitle) & ".bas")
        sb.AppendLine("' ============================================================================")
    End Sub

    Private Sub EmitIncludes(sb As StringBuilder)
        sb.AppendLine("#Ifdef __FB_LINUX__")
        sb.AppendLine("#Undef MAKELONG")
        sb.AppendLine("#Endif")
        sb.AppendLine()
        sb.AppendLine("#Include ""window9.bi""")
    End Sub

    Private Sub EmitScalingConstants(sb As StringBuilder, design As W9FormDesign)
        sb.AppendLine("' --- Base dimensions for proportional scaling ---")
        sb.AppendLine("Dim Shared As Long BaseWidth  : BaseWidth  = " & design.BaseWidth)
        sb.AppendLine("Dim Shared As Long BaseHeight : BaseHeight = " & design.BaseHeight)
        sb.AppendLine()
        sb.AppendLine("#Define ScaleX(_V) ((((_V) * WinWid) \ BaseWidth))")
        sb.AppendLine("#Define ScaleY(_V) ((((_V) * WinHei) \ BaseHeight))")
    End Sub

    Private Sub EmitLinuxCompat(sb As StringBuilder)
        sb.AppendLine("' --- Linux compatibility ---")
        sb.AppendLine("#Ifndef BS_DEFPUSHBUTTON")
        sb.AppendLine("  #Define BS_DEFPUSHBUTTON 0")
        sb.AppendLine("#Endif")
        sb.AppendLine("#Ifndef SS_CENTERIMAGE")
        sb.AppendLine("  #Define SS_CENTERIMAGE 0")
        sb.AppendLine("#Endif")
        sb.AppendLine("#Ifndef SS_NOTIFY")
        sb.AppendLine("  #Define SS_NOTIFY 0")
        sb.AppendLine("#Endif")
    End Sub

    Private Sub EmitGadgetEnum(sb As StringBuilder, design As W9FormDesign)
        sb.AppendLine("' --- Gadget IDs ---")
        sb.AppendLine("Enum GadgetID")
        sb.AppendLine("  giFirst = " & design.GadgetEnumStart)
        For Each g In design.Gadgets
            If Not String.IsNullOrEmpty(g.EnumName) Then
                sb.AppendLine("  " & g.EnumName)
            End If
        Next
        sb.AppendLine("End Enum")
    End Sub

    Private Sub EmitMenuEnum(sb As StringBuilder, design As W9FormDesign)
        sb.AppendLine("' --- Menu IDs ---")
        sb.AppendLine("Enum MenuID")
        sb.AppendLine("  miFirst = " & design.MenuEnumStart)
        For Each topMenu In design.MenuItems
            If Not String.IsNullOrEmpty(topMenu.EnumName) Then
                sb.AppendLine("  " & topMenu.EnumName)
            End If
            For Each child In topMenu.Children
                If Not String.IsNullOrEmpty(child.EnumName) Then
                    sb.AppendLine("  " & child.EnumName)
                End If
            Next
        Next
        sb.AppendLine("End Enum")
    End Sub

    Private Sub EmitShortcutEnum(sb As StringBuilder, design As W9FormDesign)
        sb.AppendLine("' --- Shortcut IDs ---")
        sb.AppendLine("Enum ShortCutID")
        sb.AppendLine("  siFirst = " & design.ShortcutEnumStart)
        sb.AppendLine("  siDefKey")
        sb.AppendLine("End Enum")
    End Sub

    Private Sub EmitSharedVars(sb As StringBuilder, design As W9FormDesign)
        sb.AppendLine("' --- Shared variables ---")
        sb.AppendLine("Dim Shared As HWND hMainForm")
        If design.MenuItems.Count > 0 Then
            sb.Append("Dim Shared As HMENU hMenu")
            For Each topMenu In design.MenuItems
                Dim varName = "h" & SanitizeVarName(topMenu.Text) & "Menu"
                sb.Append(", " & varName)
            Next
            sb.AppendLine()
        End If
        If design.HasTimer Then
            sb.AppendLine("Dim Shared As Integer Timer1")
        End If
    End Sub

    Private Sub EmitEventHandlerStubs(sb As StringBuilder, design As W9FormDesign)
        Dim hasAny = False

        ' Collect all gadgets that need event handlers
        Dim eventGadgets As New List(Of W9GadgetInstance)()
        For Each g In design.Gadgets
            Select Case g.GadgetType
                Case W9GadgetType.Button
                    eventGadgets.Add(g)  ' Buttons always get click handler
                Case Else
                    ' Other gadgets get handlers if events are enabled
                    If g.OnClickEvent OrElse g.OnChangeEvent OrElse g.OnDoubleClickEvent Then
                        eventGadgets.Add(g)
                    End If
            End Select
        Next

        If eventGadgets.Count = 0 Then Return

        sb.AppendLine("' ============================================================================")
        sb.AppendLine("' Event Handler Stubs - Add your code here")
        sb.AppendLine("' ============================================================================")
        sb.AppendLine()

        For Each g In eventGadgets
            Dim baseName = SanitizeVarName(g.EnumName.Replace("gi", ""))

            ' OnClick handler (always for Buttons, opt-in for others)
            If g.GadgetType = W9GadgetType.Button OrElse g.OnClickEvent Then
                sb.AppendLine("Sub On" & baseName & "Click()")
                Select Case g.GadgetType
                    Case W9GadgetType.Button
                        sb.AppendLine("    ' TODO: Handle " & g.EnumName & " click")
                        If Not String.IsNullOrEmpty(g.Text) Then
                            sb.AppendLine("    ' Button text: """ & g.Text & """")
                        End If
                    Case W9GadgetType.CheckBox
                        sb.AppendLine("    ' TODO: Handle " & g.EnumName & " toggle")
                        sb.AppendLine("    Dim state As Integer = GetGadgetState(" & g.EnumName & ")")
                        sb.AppendLine("    ' state: 1 = checked, 0 = unchecked")
                    Case W9GadgetType.OptionButton
                        sb.AppendLine("    ' TODO: Handle " & g.EnumName & " selection")
                    Case W9GadgetType.HyperLink
                        sb.AppendLine("    ' TODO: Handle " & g.EnumName & " click")
                    Case W9GadgetType.TextLabel
                        sb.AppendLine("    ' TODO: Handle " & g.EnumName & " click (requires SS_NOTIFY style)")
                    Case Else
                        sb.AppendLine("    ' TODO: Handle " & g.EnumName & " click")
                End Select
                sb.AppendLine("End Sub")
                sb.AppendLine()
            End If

            ' OnChange handler (ComboBox, ListBox, Editor, ScrollBar, TrackBar, Spin, StringInput)
            If g.OnChangeEvent Then
                sb.AppendLine("Sub On" & baseName & "Change()")
                Select Case g.GadgetType
                    Case W9GadgetType.ComboBox
                        sb.AppendLine("    ' TODO: Handle " & g.EnumName & " selection change")
                        sb.AppendLine("    Dim idx As Integer = GetGadgetState(" & g.EnumName & ")")
                        sb.AppendLine("    Dim txt As String = GetComboBoxText(" & g.EnumName & ")")
                    Case W9GadgetType.ListBox
                        sb.AppendLine("    ' TODO: Handle " & g.EnumName & " selection change")
                        sb.AppendLine("    Dim idx As Integer = GetGadgetState(" & g.EnumName & ")")
                        sb.AppendLine("    Dim txt As String = GetListBoxText(" & g.EnumName & ")")
                    Case W9GadgetType.Editor
                        sb.AppendLine("    ' TODO: Handle " & g.EnumName & " text change")
                        sb.AppendLine("    ' Dim txt As String = GetGadgetText(" & g.EnumName & ")")
                    Case W9GadgetType.StringInput
                        sb.AppendLine("    ' TODO: Handle " & g.EnumName & " text change")
                        sb.AppendLine("    Dim txt As String = GetGadgetText(" & g.EnumName & ")")
                    Case W9GadgetType.ScrollBar, W9GadgetType.TrackBar, W9GadgetType.SpinBox
                        sb.AppendLine("    ' TODO: Handle " & g.EnumName & " value change")
                        sb.AppendLine("    Dim value As Integer = GetGadgetState(" & g.EnumName & ")")
                    Case W9GadgetType.Calendar
                        sb.AppendLine("    ' TODO: Handle " & g.EnumName & " date selection")
                    Case W9GadgetType.PanelTab
                        sb.AppendLine("    ' TODO: Handle " & g.EnumName & " tab change")
                        sb.AppendLine("    Dim tabIdx As Integer = GetGadgetState(" & g.EnumName & ")")
                    Case Else
                        sb.AppendLine("    ' TODO: Handle " & g.EnumName & " change")
                End Select
                sb.AppendLine("End Sub")
                sb.AppendLine()
            End If

            ' OnDoubleClick handler (ListBox, ListView, TreeView, Editor)
            If g.OnDoubleClickEvent Then
                sb.AppendLine("Sub On" & baseName & "DoubleClick()")
                Select Case g.GadgetType
                    Case W9GadgetType.ListBox
                        sb.AppendLine("    ' TODO: Handle " & g.EnumName & " double-click")
                        sb.AppendLine("    Dim idx As Integer = GetGadgetState(" & g.EnumName & ")")
                        sb.AppendLine("    Dim txt As String = GetListBoxText(" & g.EnumName & ")")
                    Case W9GadgetType.ListView
                        sb.AppendLine("    ' TODO: Handle " & g.EnumName & " double-click")
                        sb.AppendLine("    ' Use EventNumberListView to get column info")
                    Case W9GadgetType.TreeView
                        sb.AppendLine("    ' TODO: Handle " & g.EnumName & " double-click")
                        sb.AppendLine("    ' Use EventNumberTreeView to get item info")
                    Case Else
                        sb.AppendLine("    ' TODO: Handle " & g.EnumName & " double-click")
                End Select
                sb.AppendLine("End Sub")
                sb.AppendLine()
            End If
        Next
    End Sub

    Private Sub EmitResizeHandler(sb As StringBuilder, design As W9FormDesign)
        sb.AppendLine("' ============================================================================")
        sb.AppendLine("' size_change - Proportional resize of all gadgets")
        sb.AppendLine("' ============================================================================")
        sb.AppendLine("Sub size_change(WinWid As Long, WinHei As Long)")

        For Each g In design.Gadgets
            ' StatusBar doesn't need resize (it auto-docks)
            If g.GadgetType = W9GadgetType.StatusBar Then Continue For

            sb.AppendLine("  ResizeGadget(" & g.EnumName & ", ScaleX(" & g.X & "), ScaleY(" & g.Y & "), ScaleX(" & g.W & "), ScaleY(" & g.H & "))")

            ' Re-apply special editor settings after resize
            If g.GadgetType = W9GadgetType.Editor Then
                If g.IsReadOnly Then
                    sb.AppendLine("  ReadOnlyEditor(" & g.EnumName & ", 1)")
                End If
                If g.WordWrap Then
                    sb.AppendLine("  SetTransferTextLineEditorGadget(" & g.EnumName & ", 1)")
                End If
            End If
        Next

        ' Font scaling
        sb.AppendLine()
        sb.AppendLine("  ' --- Scale fonts proportionally ---")
        For Each g In design.Gadgets
            If g.GadgetType = W9GadgetType.StatusBar Then Continue For
            Dim tdef = W9GadgetRegistry.GetTypeDef(g.GadgetType)
            If tdef IsNot Nothing AndAlso tdef.SupportsFont Then
                Dim fontName = If(String.IsNullOrEmpty(g.FontName), "Consolas", g.FontName)
                Dim fontSize = If(g.FontSize > 0, g.FontSize, 11)
                sb.AppendLine("  SetGadgetFont(" & g.EnumName & ", Cint(LoadFont(""" & fontName & """, ScaleY(" & fontSize & "))))")
            End If
        Next

        sb.AppendLine()
        sb.AppendLine("  UpdateInfoXserver()")
        sb.AppendLine("End Sub")
    End Sub

    Private Sub EmitMainSection(sb As StringBuilder, design As W9FormDesign)
        sb.AppendLine("' ============================================================================")
        sb.AppendLine("' MAIN - Create window and gadgets")
        sb.AppendLine("' ============================================================================")
        sb.AppendLine()

        ' Create window
        ' Note: OpenWindow dimensions = outer window size.
        ' Gadget coordinates are relative to the client area (below title bar).
        ' Title bar takes ~30px from the top, so place gadgets starting at Y >= 10.
        sb.AppendLine("' --- Create main window ---")
        sb.AppendLine("hMainForm = OpenWindow(""" & EscapeString(design.FormTitle) & """, " &
                      design.FormX & ", " & design.FormY & ", " &
                      design.FormWidth & ", " & design.FormHeight & ")")
        If design.CenterOnScreen Then
            sb.AppendLine("CenterWindow(hMainForm)")
        End If
        If design.FormColor <> Color.Empty Then
            sb.AppendLine("WindowColor(hMainForm, BGR(" & design.FormColor.R & ", " &
                          design.FormColor.G & ", " & design.FormColor.B & "))")
        End If
        sb.AppendLine()

        ' Create menus
        If design.MenuItems.Count > 0 Then
            EmitMenuCreation(sb, design)
            sb.AppendLine()
        End If

        ' Create gadgets
        sb.AppendLine("' --- Create gadgets ---")
        For Each g In design.Gadgets
            EmitGadgetCreation(sb, g)
        Next
        sb.AppendLine()

        ' Timer
        If design.HasTimer Then
            sb.AppendLine("' --- Timer ---")
            sb.AppendLine("SetTimer(hMainForm, Timer1, " & design.TimerInterval & ", NULL)")
            sb.AppendLine()
        End If

        ' Keyboard shortcut
        If design.HasKeyboardShortcut Then
            sb.AppendLine("' --- Keyboard shortcut (Enter key) ---")
            sb.AppendLine("AddKeyboardShortcut(hMainForm, FVIRTKEY, VK_RETURN, siDefKey)")
            sb.AppendLine()
        End If

        sb.AppendLine("UpdateInfoXserver()")
        sb.AppendLine()

        ' Force initial resize to fit actual client area
        ' (OpenWindow dimensions include title bar + borders, so client area is smaller)
        If design.ProportionalResize Then
            sb.AppendLine("' Force initial layout to fit actual client area")
            sb.AppendLine("size_change(WindowWidth(hMainForm), WindowHeight(hMainForm))")
        End If
    End Sub

    Private Sub EmitMenuCreation(sb As StringBuilder, design As W9FormDesign)
        sb.AppendLine("' --- Create menu bar ---")
        sb.AppendLine("hMenu = Create_Menu()")
        For Each topMenu In design.MenuItems
            Dim varName = "h" & SanitizeVarName(topMenu.Text) & "Menu"
            sb.AppendLine(varName & " = MenuTitle(hMenu, """ & EscapeString(topMenu.Text) & """)")
            For Each child In topMenu.Children
                If child.IsSeparator Then
                    sb.AppendLine("    MenuItem(" & child.EnumName & ", " & varName & ", ""-"")")
                Else
                    sb.AppendLine("    MenuItem(" & child.EnumName & ", " & varName & ", """ & EscapeString(child.Text) & """)")
                End If
            Next
        Next
    End Sub

    Private Sub EmitGadgetCreation(sb As StringBuilder, g As W9GadgetInstance)
        Dim tdef = W9GadgetRegistry.GetTypeDef(g.GadgetType)
        If tdef Is Nothing Then Return

        ' Comment
        sb.AppendLine()
        sb.AppendLine("' --- " & tdef.DisplayName & ": " & g.EnumName & " ---")

        ' Build the creation call based on gadget type
        Select Case g.GadgetType
            Case W9GadgetType.Button
                Dim style = If(String.IsNullOrEmpty(g.Style), "BS_DEFPUSHBUTTON", g.Style)
                sb.AppendLine(tdef.W9FunctionName & "(" & g.EnumName & ", " &
                              g.X & ", " & g.Y & ", " & g.W & ", " & g.H & ", """ &
                              EscapeString(g.Text) & """, " & style & ")")

            Case W9GadgetType.TextLabel
                Dim style = If(String.IsNullOrEmpty(g.Style), "SS_NOTIFY", g.Style)
                sb.AppendLine(tdef.W9FunctionName & "(" & g.EnumName & ", " &
                              g.X & ", " & g.Y & ", " & g.W & ", " & g.H & ", """ &
                              EscapeString(g.Text) & """, " & style & ")")

            Case W9GadgetType.Editor
                ' Build editor style flags
                Dim edStyle = "ES_MULTILINE"
                If g.HasVScroll Then edStyle &= " Or WS_VSCROLL"
                If g.HasHScroll Then edStyle &= " Or WS_HSCROLL"
                sb.AppendLine(tdef.W9FunctionName & "(" & g.EnumName & ", " &
                              g.X & ", " & g.Y & ", " & g.W & ", " & g.H & ", """ &
                              EscapeString(g.Text) & """, " & edStyle & ")")
                If g.IsReadOnly Then
                    sb.AppendLine("ReadOnlyEditor(" & g.EnumName & ", 1)")
                End If
                If g.WordWrap Then
                    sb.AppendLine("SetTransferTextLineEditorGadget(" & g.EnumName & ", 1)")
                End If

            Case W9GadgetType.StringInput
                If g.IsPassword Then
                    sb.AppendLine(tdef.W9FunctionName & "(" & g.EnumName & ", " &
                                  g.X & ", " & g.Y & ", " & g.W & ", " & g.H & ", """ &
                                  EscapeString(g.Text) & """, ES_PASSWORD)")
                Else
                    sb.AppendLine(tdef.W9FunctionName & "(" & g.EnumName & ", " &
                                  g.X & ", " & g.Y & ", " & g.W & ", " & g.H & ", """ &
                                  EscapeString(g.Text) & """)")
                End If

            Case W9GadgetType.CheckBox
                sb.AppendLine(tdef.W9FunctionName & "(" & g.EnumName & ", " &
                              g.X & ", " & g.Y & ", " & g.W & ", " & g.H & ", """ &
                              EscapeString(g.Text) & """)")
                If g.IsChecked Then
                    sb.AppendLine("SetGadgetState(" & g.EnumName & ", 1)")
                End If

            Case W9GadgetType.OptionButton
                sb.AppendLine(tdef.W9FunctionName & "(" & g.EnumName & ", " &
                              g.X & ", " & g.Y & ", " & g.W & ", " & g.H & ", """ &
                              EscapeString(g.Text) & """)")
                If g.IsChecked Then
                    sb.AppendLine("SetGadgetState(" & g.EnumName & ", 1)")
                End If

            Case W9GadgetType.ComboBox
                sb.AppendLine(tdef.W9FunctionName & "(" & g.EnumName & ", " &
                              g.X & ", " & g.Y & ", " & g.W & ", " & g.H & ")")
                ' Add initial items
                If Not String.IsNullOrEmpty(g.Items) Then
                    For Each item In g.Items.Split({vbCrLf, vbLf, vbCr}, StringSplitOptions.RemoveEmptyEntries)
                        sb.AppendLine("AddComboBoxItem(" & g.EnumName & ", """ & EscapeString(item.Trim()) & """, -1)")
                    Next
                End If

            Case W9GadgetType.ListBox
                sb.AppendLine(tdef.W9FunctionName & "(" & g.EnumName & ", " &
                              g.X & ", " & g.Y & ", " & g.W & ", " & g.H & ")")
                ' Add initial items
                If Not String.IsNullOrEmpty(g.Items) Then
                    For Each item In g.Items.Split({vbCrLf, vbLf, vbCr}, StringSplitOptions.RemoveEmptyEntries)
                        sb.AppendLine("AddListBoxItem(" & g.EnumName & ", """ & EscapeString(item.Trim()) & """)")
                    Next
                End If

            Case W9GadgetType.GroupBox
                sb.AppendLine(tdef.W9FunctionName & "(" & g.EnumName & ", " &
                              g.X & ", " & g.Y & ", " & g.W & ", " & g.H & ", """ &
                              EscapeString(g.Text) & """)")

            Case W9GadgetType.ImageBox
                sb.AppendLine(tdef.W9FunctionName & "(" & g.EnumName & ", " &
                              g.X & ", " & g.Y & ", " & g.W & ", " & g.H & ")")
                If Not String.IsNullOrEmpty(g.ImagePath) Then
                    sb.AppendLine("' TODO: Load image - Var hImg = Load_Image(""" & EscapeString(g.ImagePath) & """)")
                    sb.AppendLine("' SetImageGadget(" & g.EnumName & ", hImg)")
                End If

            Case W9GadgetType.ProgressBar
                sb.AppendLine(tdef.W9FunctionName & "(" & g.EnumName & ", " &
                              g.X & ", " & g.Y & ", " & g.W & ", " & g.H & ", " &
                              g.MinValue & ", " & g.MaxValue & ")")
                If g.CurrentValue > 0 Then
                    sb.AppendLine("SetGadgetState(" & g.EnumName & ", " & g.CurrentValue & ")")
                End If

            Case W9GadgetType.ScrollBar
                Dim style = If(g.Orientation = 1, "SB_VERT", "SB_HORZ")
                sb.AppendLine(tdef.W9FunctionName & "(" & g.EnumName & ", " &
                              g.X & ", " & g.Y & ", " & g.W & ", " & g.H & ", " &
                              g.MinValue & ", " & g.MaxValue & ", " & style & ")")

            Case W9GadgetType.TrackBar
                sb.AppendLine(tdef.W9FunctionName & "(" & g.EnumName & ", " &
                              g.X & ", " & g.Y & ", " & g.W & ", " & g.H & ", " &
                              g.MinValue & ", " & g.MaxValue & ")")
                If g.CurrentValue > 0 Then
                    sb.AppendLine("SetGadgetState(" & g.EnumName & ", " & g.CurrentValue & ")")
                End If

            Case W9GadgetType.SpinBox
                sb.AppendLine(tdef.W9FunctionName & "(" & g.EnumName & ", " &
                              g.X & ", " & g.Y & ", " & g.W & ", " & g.H & ", " &
                              g.MaxValue & ", " & g.MinValue & ", " & g.CurrentValue & ")")

            Case W9GadgetType.TreeView
                ' Build TreeView style flags
                Dim tvStyle = ""
                If g.HasLines Then tvStyle = "TVS_HASLINES Or TVS_LINESATROOT"
                If g.HasButtons Then
                    tvStyle = If(tvStyle = "", "TVS_HASBUTTONS", tvStyle & " Or TVS_HASBUTTONS")
                End If
                If g.HasCheckBoxes Then
                    tvStyle = If(tvStyle = "", "TVS_CHECKBOXES", tvStyle & " Or TVS_CHECKBOXES")
                End If
                If tvStyle = "" Then tvStyle = "0"
                sb.AppendLine(tdef.W9FunctionName & "(" & g.EnumName & ", " &
                              g.X & ", " & g.Y & ", " & g.W & ", " & g.H & ", " &
                              tvStyle & ", WS_EX_CLIENTEDGE, 16)")

            Case W9GadgetType.ListView
                sb.AppendLine(tdef.W9FunctionName & "(" & g.EnumName & ", " &
                              g.X & ", " & g.Y & ", " & g.W & ", " & g.H & ")")
                ' ListView columns
                For i = 0 To g.ListViewColumns.Count - 1
                    sb.AppendLine("AddListViewColumn(" & g.EnumName & ", """ &
                                  EscapeString(g.ListViewColumns(i)) & """, " & i & ", 120)")
                Next
                ' Extended styles
                If g.FullRowSelect OrElse g.HasCheckBoxes Then
                    Dim exFlags = ""
                    If g.FullRowSelect Then exFlags = "LVS_EX_FULLROWSELECT"
                    If g.HasCheckBoxes Then
                        exFlags = If(exFlags = "", "LVS_EX_CHECKBOXES", exFlags & " Or LVS_EX_CHECKBOXES")
                    End If
                    sb.AppendLine("SetListViewExtendedStyle(" & g.EnumName & ", " & exFlags & ")")
                End If

            Case W9GadgetType.StatusBar
                sb.AppendLine(tdef.W9FunctionName & "(" & g.EnumName & ")")
                For i = 0 To g.StatusBarFields.Count - 1
                    Dim f = g.StatusBarFields(i)
                    sb.AppendLine("SetStatusBarField(" & g.EnumName & ", " & i & ", " &
                                  f.Width & ", """ & EscapeString(f.Text) & """)")
                Next

            Case W9GadgetType.PanelTab
                sb.AppendLine(tdef.W9FunctionName & "(" & g.EnumName & ", " &
                              g.X & ", " & g.Y & ", " & g.W & ", " & g.H & ")")
                ' Add tab pages
                If Not String.IsNullOrEmpty(g.TabNames) Then
                    Dim tabs = g.TabNames.Split({vbCrLf, vbLf, vbCr}, StringSplitOptions.RemoveEmptyEntries)
                    For i = 0 To tabs.Length - 1
                        sb.AppendLine("Var hTab" & g.EnumName.Replace("gi", "") & i & " = AddPanelGadgetItem(" &
                                      g.EnumName & ", " & i & ", """ & EscapeString(tabs(i).Trim()) & """)")
                    Next
                End If

            Case W9GadgetType.Container
                sb.AppendLine(tdef.W9FunctionName & "(" & g.EnumName & ", " &
                              g.X & ", " & g.Y & ", " & g.W & ", " & g.H & ")")

            Case W9GadgetType.Calendar
                sb.AppendLine(tdef.W9FunctionName & "(" & g.EnumName & ", " &
                              g.X & ", " & g.Y & ", " & g.W & ", " & g.H & ")")

            Case W9GadgetType.HyperLink
                sb.AppendLine(tdef.W9FunctionName & "(" & g.EnumName & ", " &
                              g.X & ", " & g.Y & ", " & g.W & ", " & g.H & ", """ &
                              EscapeString(g.Text) & """)")

            Case Else
                sb.AppendLine("' Unsupported gadget type: " & g.GadgetType.ToString())
        End Select

        ' Font — always set explicitly so gadgets have consistent appearance
        If tdef.SupportsFont Then
            Dim fontName = If(String.IsNullOrEmpty(g.FontName), "Consolas", g.FontName)
            Dim fontSize = If(g.FontSize > 0, g.FontSize, 11)
            sb.AppendLine("SetGadgetFont(" & g.EnumName & ", Cint(LoadFont(""" & fontName & """, " & fontSize & ")))")
        End If

        ' Colors
        If g.BackColor <> Color.Empty Then
            sb.AppendLine("SetGadgetColor(" & g.EnumName & ", BGR(" &
                          g.BackColor.R & ", " & g.BackColor.G & ", " & g.BackColor.B & "), 0, 3)")
        End If
        If g.ForeColor <> Color.Empty Then
            sb.AppendLine("SetGadgetColor(" & g.EnumName & ", BGR(" &
                          g.ForeColor.R & ", " & g.ForeColor.G & ", " & g.ForeColor.B & "), 1, 3)")
        End If

        ' Tooltip
        If Not String.IsNullOrEmpty(g.Tooltip) Then
            sb.AppendLine("GadgetToolTip(" & g.EnumName & ", """ & EscapeString(g.Tooltip) & """)")
        End If

        ' Enabled/Visible state
        If Not g.IsEnabled Then
            sb.AppendLine("DisableGadget(" & g.EnumName & ", 1)")
        End If
        If Not g.IsVisible Then
            sb.AppendLine("HideGadget(" & g.EnumName & ", 1)")
        End If
    End Sub

    Private Sub EmitEventLoop(sb As StringBuilder, design As W9FormDesign)
        sb.AppendLine("' ============================================================================")
        sb.AppendLine("' EVENT LOOP")
        sb.AppendLine("' ============================================================================")
        sb.AppendLine("Do")
        sb.AppendLine("    Select Case WaitEvent()")
        sb.AppendLine()

        ' Resize event
        If design.HandleResize AndAlso design.ProportionalResize Then
            sb.AppendLine("    Case EventSize")
            sb.AppendLine("        If EventHwnd = hMainForm Then")
            sb.AppendLine("            size_change(WindowWidth(hMainForm), WindowHeight(hMainForm))")
            sb.AppendLine("        End If")
            sb.AppendLine()
        End If

        ' Menu event
        If design.MenuItems.Count > 0 OrElse design.HasKeyboardShortcut Then
            sb.AppendLine("    Case EventMenu")
            sb.AppendLine("        Select Case EventNumber")
            If design.HasKeyboardShortcut Then
                ' Find the default button handler
                Dim defaultBtn = design.Gadgets.Find(Function(g) g.ID = design.DefaultButtonID)
                If defaultBtn IsNot Nothing Then
                    Dim handlerName = SanitizeVarName(defaultBtn.EnumName.Replace("gi", "On")) & "Click"
                    sb.AppendLine("        Case siDefKey")
                    sb.AppendLine("            " & handlerName & "()")
                Else
                    sb.AppendLine("        Case siDefKey")
                    sb.AppendLine("            ' TODO: Handle Enter key")
                End If
            End If
            For Each topMenu In design.MenuItems
                For Each child In topMenu.Children
                    If Not child.IsSeparator Then
                        sb.AppendLine("        Case " & child.EnumName)
                        sb.AppendLine("            ' TODO: Handle " & child.Text)
                    End If
                Next
            Next
            sb.AppendLine("        End Select")
            sb.AppendLine()
        End If

        ' Timer event
        If design.HasTimer Then
            sb.AppendLine("    Case EventTimer")
            sb.AppendLine("        ' TODO: Handle timer tick")
            sb.AppendLine()
        End If

        ' Close event
        sb.AppendLine("    Case EventClose")
        If design.HasTimer Then
            sb.AppendLine("        KillTimer(hMainForm, Timer1)")
        End If
        sb.AppendLine("        End")
        sb.AppendLine()

        ' Gadget events (click, change, etc.)
        Dim clickGadgets = design.Gadgets.FindAll(Function(g)
                                                      Return g.GadgetType = W9GadgetType.Button OrElse
                                                             g.OnClickEvent OrElse g.OnChangeEvent OrElse
                                                             g.OnDoubleClickEvent
                                                  End Function)
        If clickGadgets.Count > 0 Then
            sb.AppendLine("    Case EventGadget")
            sb.AppendLine("        Select Case EventNumber")
            For Each g In clickGadgets
                Dim baseName = SanitizeVarName(g.EnumName.Replace("gi", ""))

                sb.AppendLine("        Case " & g.EnumName)

                ' For gadgets with both click and change, use EventKey to differentiate
                If (g.GadgetType = W9GadgetType.Button OrElse g.OnClickEvent) AndAlso
                   Not g.OnChangeEvent AndAlso Not g.OnDoubleClickEvent Then
                    ' Simple click only
                    sb.AppendLine("            On" & baseName & "Click()")
                ElseIf g.OnClickEvent AndAlso g.OnChangeEvent Then
                    ' Both click and change - some gadgets use EventKey
                    sb.AppendLine("            On" & baseName & "Click()")
                    sb.AppendLine("            On" & baseName & "Change()")
                ElseIf g.OnChangeEvent AndAlso Not g.OnClickEvent Then
                    ' Change only
                    sb.AppendLine("            On" & baseName & "Change()")
                ElseIf g.GadgetType = W9GadgetType.Button Then
                    sb.AppendLine("            On" & baseName & "Click()")
                End If

                ' Double-click handling note
                If g.OnDoubleClickEvent Then
                    sb.AppendLine("            ' Note: For double-click, check EventKey or use a timer")
                    sb.AppendLine("            ' On" & baseName & "DoubleClick()")
                End If
            Next
            sb.AppendLine("        End Select")
            sb.AppendLine()
        End If

        sb.AppendLine("    End Select")
        sb.AppendLine("Loop")
    End Sub

    ' =========================================================================
    ' Helpers
    ' =========================================================================

    Private Sub EmitHelperReference(sb As StringBuilder, design As W9FormDesign)
        ' Build a list of which gadget types are used
        Dim usedTypes As New HashSet(Of W9GadgetType)()
        For Each g In design.Gadgets
            usedTypes.Add(g.GadgetType)
        Next

        sb.AppendLine("' ============================================================================")
        sb.AppendLine("' Window9 API Quick Reference (for gadgets used in this form)")
        sb.AppendLine("' ============================================================================")

        ' Common functions
        sb.AppendLine("' Common:")
        sb.AppendLine("'   GetGadgetText(gadgetID) -> String")
        sb.AppendLine("'   SetGadgetText(gadgetID, ""text"")")
        sb.AppendLine("'   GetGadgetState(gadgetID) -> Integer")
        sb.AppendLine("'   SetGadgetState(gadgetID, value)")
        sb.AppendLine("'   DisableGadget(gadgetID, 1)  /  DisableGadget(gadgetID, 0)")
        sb.AppendLine("'   HideGadget(gadgetID, 1)  /  HideGadget(gadgetID, 0)")
        sb.AppendLine("'   SetFocus(GadgetID(gadgetID))")
        sb.AppendLine("'   GadgetToolTip(gadgetID, ""tooltip text"")")
        sb.AppendLine("'   FreeGadget(gadgetID)")

        If usedTypes.Contains(W9GadgetType.Editor) Then
            sb.AppendLine("' Editor:")
            sb.AppendLine("'   GetGadgetText(id) -> full text  |  SetGadgetText(id, ""text"")")
            sb.AppendLine("'   GetLineTextEditor(id, lineNum) -> String")
            sb.AppendLine("'   GetLineCountEditor(id) -> Integer")
            sb.AppendLine("'   GetSelectTextEditorGadget(id) -> String")
            sb.AppendLine("'   GetModifyEditor(id) -> Integer (1=modified)")
            sb.AppendLine("'   PasteEditor(id)  |  ReadOnlyEditor(id, 1/0)")
            sb.AppendLine("'   SetTransferTextLineEditorGadget(id, 1) ' word wrap")
        End If

        If usedTypes.Contains(W9GadgetType.ComboBox) Then
            sb.AppendLine("' ComboBox:")
            sb.AppendLine("'   AddComboBoxItem(id, ""text"", position)  ' -1 = end")
            sb.AppendLine("'   DeleteComboBoxItem(id, index)")
            sb.AppendLine("'   GetComboBoxText(id) -> String")
            sb.AppendLine("'   GetItemComboBox(id, index) -> String")
            sb.AppendLine("'   CountItemComboBox(id) -> Integer")
            sb.AppendLine("'   ResetAllComboBox(id)  ' clear all items")
            sb.AppendLine("'   SetComboBoxItemText(id, ""newtext"", index)")
        End If

        If usedTypes.Contains(W9GadgetType.ListBox) Then
            sb.AppendLine("' ListBox:")
            sb.AppendLine("'   AddListBoxItem(id, ""text"")")
            sb.AppendLine("'   GetListBoxText(id) -> String (selected item)")
            sb.AppendLine("'   GetItemListBox(id, index) -> String")
            sb.AppendLine("'   CountItemListBox(id) -> Integer")
            sb.AppendLine("'   ResetAllListBox(id)  ' clear all items")
            sb.AppendLine("'   GetSelCountListBox(id) -> Integer (multi-select)")
        End If

        If usedTypes.Contains(W9GadgetType.ListView) Then
            sb.AppendLine("' ListView:")
            sb.AppendLine("'   AddListViewColumn(id, ""header"", colIndex, width)")
            sb.AppendLine("'   AddListViewItem(id, ""text"", rowIndex)")
            sb.AppendLine("'   ReplaceTextColumnListView(id, ""text"", row, col)")
            sb.AppendLine("'   GetItemListView(id, row, col) -> String")
            sb.AppendLine("'   GetItemCountListView(id) -> Integer")
            sb.AppendLine("'   DeleteItemListView(id, row)")
        End If

        If usedTypes.Contains(W9GadgetType.TreeView) Then
            sb.AppendLine("' TreeView:")
            sb.AppendLine("'   AddTreeViewItem(id, ""text"", img1, img2, pos)")
            sb.AppendLine("'   AddTreeViewItem(id, ""text"", img1, img2, pos, parentItem)")
            sb.AppendLine("'   GetItemTreeView(id) -> String (selected item text)")
            sb.AppendLine("'   GetCountItemTreeView(id) -> Integer")
            sb.AppendLine("'   RenameItemTreeView(id, ""newtext"")")
        End If

        If usedTypes.Contains(W9GadgetType.ProgressBar) Then
            sb.AppendLine("' ProgressBar:")
            sb.AppendLine("'   SetGadgetState(id, value)  ' set position")
            sb.AppendLine("'   SetRangeProgressBar(id, min, max)")
        End If

        If usedTypes.Contains(W9GadgetType.ScrollBar) OrElse usedTypes.Contains(W9GadgetType.TrackBar) Then
            sb.AppendLine("' ScrollBar/TrackBar:")
            sb.AppendLine("'   GetGadgetState(id) -> Integer (current position)")
            sb.AppendLine("'   SetGadgetState(id, value)")
            sb.AppendLine("'   SetTrackBarMinPos(id, min)  |  SetTrackBarMaxPos(id, max)")
        End If

        If usedTypes.Contains(W9GadgetType.ImageBox) Then
            sb.AppendLine("' Image:")
            sb.AppendLine("'   Var img = Load_Image(""filename.bmp"")")
            sb.AppendLine("'   SetImageGadget(id, img)")
            sb.AppendLine("'   Resize_Image(img, newWidth, newHeight)")
            sb.AppendLine("'   Free_Image(img)")
        End If

        If usedTypes.Contains(W9GadgetType.PanelTab) Then
            sb.AppendLine("' PanelTab:")
            sb.AppendLine("'   Var hTab = AddPanelGadgetItem(id, index, ""Tab Name"")")
            sb.AppendLine("'   UseGadgetList(hTab)  ' add gadgets to this tab")
            sb.AppendLine("'   GetGadgetState(id) -> Integer (selected tab index)")
        End If

        If usedTypes.Contains(W9GadgetType.StatusBar) Then
            sb.AppendLine("' StatusBar:")
            sb.AppendLine("'   SetStatusBarField(id, fieldIndex, width, ""text"")")
        End If

        sb.AppendLine("' Dialogs:")
        sb.AppendLine("'   OpenFileRequester(""Title"", startDir, ""Filter|*.ext|"") -> String")
        sb.AppendLine("'   SaveFileRequester(""Title"", startDir, ""Filter|*.ext|"") -> String")
        sb.AppendLine("'   ColorRequester(defaultColor) -> Long")
        sb.AppendLine("'   MessageRequester(""Title"", ""Message"", flags) -> Integer")
        sb.AppendLine("'   InputRequester(""Title"", ""Prompt"", ""Default"") -> String")
    End Sub

    Private Function EscapeString(s As String) As String
        If s Is Nothing Then Return ""
        Return s.Replace("""", """""").Replace(vbCr, "").Replace(vbLf, """ + Chr(10) + """)
    End Function

    Private Function SanitizeVarName(s As String) As String
        If s Is Nothing Then Return "Unknown"
        Dim result As New StringBuilder()
        For Each c In s
            If Char.IsLetterOrDigit(c) Then
                result.Append(c)
            End If
        Next
        If result.Length = 0 Then Return "Unknown"
        Return result.ToString()
    End Function

    Private Function SanitizeFilename(s As String) As String
        If s Is Nothing Then Return "untitled"
        Dim result As New StringBuilder()
        For Each c In s
            If Char.IsLetterOrDigit(c) OrElse c = "_"c OrElse c = "-"c Then
                result.Append(c)
            ElseIf c = " "c Then
                result.Append("_")
            End If
        Next
        If result.Length = 0 Then Return "untitled"
        Return result.ToString().ToLower()
    End Function

End Module
